//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suket.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Notification {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Notification() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Suket.Resources.Notification", typeof(Notification).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   この度ご応募していたPostの開催が募集者によってキャンセルされました。
        ///
        ///参加費をお支払いの場合、本日中に全額返金いたしますのでご確認ください。
        ///
        ///引き続きMint SPORTSをよろしくお願いします。
        ///
        ///中止になったPost
        ///======================
        ///開催日時：{0}
        ///開催場所：{1}
        ///リンク：&lt;a href=&quot;{2}&quot;&gt;{2}&lt;/a&gt;
        ///======================
        ///
        ///Mint SPORTSサポートチーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CancelBody {
            get {
                return ResourceManager.GetString("CancelBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}さん!&lt;br&gt;&lt;br&gt;{1}していたPostに{2}がコメントをしました。&lt;br&gt;「{3}」&lt;br&gt;&lt;br&gt;詳細は下記URLからお確かめください。&lt;br&gt;&lt;a href=&quot;https://mintsports.net/Posts/Details/{4}&quot;&gt;https://mintsports.net/Posts/Details/{4}&lt;/a&gt;&lt;br&gt;&lt;br&gt;このメールは返信不可です。&lt;br&gt;&lt;br&gt;引き続き本サービスをよろしくお願いいたします。&lt;br&gt;Mint SPORTSサポートチーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NewCommentNotificationBody {
            get {
                return ResourceManager.GetString("NewCommentNotificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   あなたの投稿に新たなコメントがありました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NewCommentNotificationSubject {
            get {
                return ResourceManager.GetString("NewCommentNotificationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}さんからメッセージが届いています。
        ///
        ///「{1}」
        ///
        ///チャット内容を確認して返信しましょう。
        ///https://mintspots.net/Chat/ChatRooms
        ///
        ///Mint SPORTSサポートチーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NewMessageBody {
            get {
                return ResourceManager.GetString("NewMessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【メッセージ】{0}さんから届きました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NewMessageSubject {
            get {
                return ResourceManager.GetString("NewMessageSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   あなたのPostに応募したユーザーがいます。
        ///
        ///ユーザーを確認して、希望通りなら採用してみましょう。
        ///&lt;a href=&quot;https://mintsports.net/Posts/MyDashboard&quot;&gt;https://mintsports.net/Posts/MyDashboard&lt;/a&gt;
        ///
        ///応募があったPost
        ///====================
        ///開催日時：{0}
        ///開催場所：{1}
        ///====================
        ///
        ///引き続きMint SPORTSをよろしくお願いします。
        ///
        ///Mint SPORTSサポートチーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SubscriptionBody {
            get {
                return ResourceManager.GetString("SubscriptionBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   あなたのPostに応募がありました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SubscriptionSubject {
            get {
                return ResourceManager.GetString("SubscriptionSubject", resourceCulture);
            }
        }
    }
}
